# Generated by Django 5.0.6 on 2024-05-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('job_number', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=100)),
                ('applied_dt', models.DateTimeField(auto_now_add=True)),
                ('payrate', models.CharField(max_length=20)),
                ('location_type', models.CharField(max_length=20)),
                ('job_url', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('contractor_name', models.CharField(max_length=100)),
                ('job_source', models.CharField(max_length=50)),
            ],
        ),
    ]
