# Generated by Django 5.0.6 on 2024-06-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0002_jobapp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='applied_dt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='contractor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='job_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='job_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='job_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='location_type',
            field=models.CharField(choices=[('ONSITE', 'Onsite'), ('HYBRID', 'Hybrid'), ('REMOTE', 'Remote')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='payrate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
