# Generated by Django 5.0.6 on 2024-06-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0005_jobapp_job_status_alter_jobapp_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapp',
            name='created_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
