# Generated by Django 5.0.6 on 2024-06-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0006_jobapp_created_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='job_status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Qualified', 'Qualified'), ('Interviewed', 'Interviewed'), ('Closed', 'Closed'), ('Offered', 'Offered')], default='APPLIED', max_length=15),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='location_type',
            field=models.CharField(choices=[('Onsite', 'Onsite'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=10),
        ),
    ]
