# Generated by Django 5.0.6 on 2024-07-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0007_alter_jobapp_job_status_alter_jobapp_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
