# Generated by Django 6.1 on 2026-08-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0008_alter_jobapp_created_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='location_type',
            field=models.CharField(choices=[('Onsite', 'Onsite'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote'), ('Unknown', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='state',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
