# Generated by Django 6.1 on 2026-08-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0009_alter_jobapp_location_type_alter_jobapp_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('change_dt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
