# Generated by Django 6.1 on 2026-08-22 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0011_jobcomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcomment',
            name='jobapp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobapps.jobapp'),
        ),
    ]
