# Generated by Django 6.1 on 2026-08-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0012_jobcomment_jobapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapp',
            name='locality',
            field=models.CharField(blank=True, default='unknown', max_length=50),
        ),
    ]
