# Generated by Django 6.1 on 2026-08-27 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0013_jobapp_locality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapp',
            old_name='job_number',
            new_name='job_id',
        ),
    ]
