# Generated by Django 6.1 on 2026-09-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0014_rename_job_number_jobapp_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='applied_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='job_status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Qualified', 'Qualified'), ('Interviewed', 'Interviewed'), ('Closed', 'Closed'), ('Offered', 'Offered')], default='Applied', max_length=15),
        ),
        migrations.AlterField(
            model_name='jobcomment',
            name='change_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
